// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpowh1YeSvI0GNuG7Neq0B6Kxg4b2hB3Q',
    appId: '1:144773354877:web:2577786e369cd82f042814',
    messagingSenderId: '144773354877',
    projectId: 'my-firebase-app-a56f0',
    authDomain: 'my-firebase-app-a56f0.firebaseapp.com',
    storageBucket: 'my-firebase-app-a56f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJwE9GiFIl1ASIfoRlxuGZxo3CXVfbiu0',
    appId: '1:144773354877:android:8de9241d3f7e18f5042814',
    messagingSenderId: '144773354877',
    projectId: 'my-firebase-app-a56f0',
    storageBucket: 'my-firebase-app-a56f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRQ3cofFcCji_Q6g-gQhzA4jxh1m2cMw8',
    appId: '1:144773354877:ios:3f44305d766747bd042814',
    messagingSenderId: '144773354877',
    projectId: 'my-firebase-app-a56f0',
    storageBucket: 'my-firebase-app-a56f0.appspot.com',
    iosClientId:
        '144773354877-iql80qu7clht7qi5ob65364r6g992krh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRQ3cofFcCji_Q6g-gQhzA4jxh1m2cMw8',
    appId: '1:144773354877:ios:3f44305d766747bd042814',
    messagingSenderId: '144773354877',
    projectId: 'my-firebase-app-a56f0',
    storageBucket: 'my-firebase-app-a56f0.appspot.com',
    iosClientId:
        '144773354877-iql80qu7clht7qi5ob65364r6g992krh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistCrud',
  );
}
